### ISSUE TITLE
NameSpace Issue

### ISSUE THREAD

**Issue by mgraf2** [STIXProject/openioc-to-stix#16]
Hello,

The script as is does not work (both openioc-to-stix and openioc-to-cybox), they return the following error:
Traceback (most recent call last):
  File "openioc-to-stix.py", line 106, in <module>
    main()
  File "openioc-to-stix.py", line 85, in main
    stix.utils.set_id_namespace(ns)
AttributeError: 'module' object has no attribute 'set_id_namespace'

If you fix the namespace error, you then get the following error:

TypeError: Indicators must be a <class 'stix.core.Indicators'>, not a <type 'list'>

**Comment by gtback** [comment]
Thanks, @mgraf2. 

I'm guessing that openioc-to-stix wasn't updated to work with the latest version of python-stix. I'll take a look at this. In the meantime, you can try installing older versions of python-stix (1.2.0.0) and python-cybox (2.1.0.12) and see if that helps.
