### ISSUE TITLE
Email Attachment type throws an exception

### ISSUE THREAD

**Issue by khodges42** [STIXProject/openioc-to-stix#17]
Related to line 247 in objectify.py,
email.add_related(attachment) should include the relationship type. Worked around this by changing that like to email.add_related(attachment, "Related_To")

**Comment by gtback** [comment]
Thanks, @khodges42. Should be a pretty easy fix.

Do you happen to have an example OpenIOC doc that demonstrates this? I'd like to add a test so this error doesn't re-occur. If you don't, no worries, I can probably create one easily enough.

**Comment by khodges42** [comment]
Hi @gtback, thank you for getting back to me! Here's one of the IOCs that was throwing the email exception https://www.iocbucket.com/iocs/9c2a7a3b3c8ea33d8e05ad2f0557cd56b5828a51
